# Project Information
site_name: manual.bt-trx.com
site_url: 'https://manual.bt-trx.com'

# Repository
repo_name: 'bt-trx/manual.bt-trx.com'
repo_url: https://github.com/bt-trx/manual.bt-trx.com

# Configuration
theme:
  name: material
  palette:
    primary: 'white'
    accent: 'light blue'
  logo: 'https://bt-trx.com/assets/img/bt-trx_quadrat.svg'
  favicon: 'https://bt-trx.com/assets/favicon.ico'
  font: false

# Customization
plugins:
  - pdf-export:
      verbose: false
      combined: true
      enabled_if_env: ENABLE_PDF_EXPORT
extra:
  version: 0.2.0
  social:
    - type: 'github'
      link: 'https://github.com/bt-trx'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
nav:
  - Startseite: index.md
  - Allgemein:
    - Kompatibilitätsliste: 10_Allgemein/Kompatibilitätsliste.md
    - Stromverbrauch: 10_Allgemein/Stromverbrauch.md
  - Zusammenbau:
    - Lötanleitung: 20_Zusammenbau/Lötanleitung.md
    - Frontblende: 20_Zusammenbau/Frontblende.md
    - Anschlusskabel: 20_Zusammenbau/Anschlusskabel.md
    - PTT-Taste: 20_Zusammenbau/PTT-Taste.md
  - Bedienung:
    - Anschluss: 30_Bedienung/Anschluss.md
    - Funkbetrieb: 30_Bedienung/Funkbetrieb.md
    - Firmware-Update: 30_Bedienung/Firmware-Update.md
  - Entwicklung:
    - Debugschnittstelle: 40_Entwicklung/Debugschnittstelle.md
    - Software: 40_Entwicklung/Software.md
    - Hardware: 40_Entwicklung/Hardware.md
