site_name: manual.bt-trx.com
theme:
  name: rtd-dropdown
  custom_dir: custom_theme/
  collapse_by_default: true
repo_url: https://github.com/bt-trx/manual.bt-trx.com
extra_css:
    - css/extra.css
extra:
  version: 0.1.0
nav:
  - Startseite: index.md
  - Allgemein:
    - Kompatibilitätsliste: 10_Allgemein/Kompatibilitätsliste.md
  - Zusammenbau:
    - Lötanleitung: 20_Zusammenbau/Lötanleitung.md
    - Anschlusskabel: 20_Zusammenbau/Anschlusskabel.md
    - PTT-Taste: 20_Zusammenbau/PTT-Taste.md
  - Bedienung:
    - Anschluss: 30_Bedienung/Anschluss.md
    - Funkbetrieb: 30_Bedienung/Funkbetrieb.md
    - Firmware-Update: 30_Bedienung/Firmware-Update.md